// config.js — Solirius Data & AI Practice bid filters
// Edit this file to adjust what tenders are surfaced

export const config = {
  // ── API ──────────────────────────────────────────────────────────────────
  baseUrl: "https://www.contractsfinder.service.gov.uk",
  rateLimit: 1200, // ms between requests (stay well under the 5-min ban threshold)

  // ── SEARCH DEFAULTS ──────────────────────────────────────────────────────
  // planning = Future Opportunity + Early Market Engagement
  // tender   = Opportunity (live ITT)
  // Amendments, awards and contract notices are excluded in filter.js
  defaultStages: ["planning", "tender"],
  defaultLookbackDays: 30,
  pageSize: 100,

  // ── KEYWORD FILTERS (case-insensitive, any match = include) ─────────────
  // Tuned for Solirius's core sectors: data/AI, housing, justice tech,
  // education data, architecture & delivery — drawn from awarded contract history.
  keywords: {

    // ── Data engineering & analytics ─────────────────────────────────────
    data: [
      // Platforms & architecture
      "data platform",
      "data strategy",
      "data architecture",
      "data mesh",
      "data fabric",
      "data lake",
      "data lakehouse",
      "data warehouse",
      "data mart",
      "data product",
      "modern data stack",
      // Engineering & pipelines
      "data engineering",
      "data pipeline",
      "data integration",
      "data ingestion",
      "ETL",
      "ELT",
      "data migration",
      "data transformation",
      "data ops",
      "DataOps",
      "real-time data",
      "streaming data",
      "event-driven",
      "Kafka",
      "Spark",
      "Databricks",
      "Snowflake",
      "dbt",
      // Governance & quality
      "data governance",
      "data quality",
      "data catalogue",
      "data lineage",
      "metadata management",
      "master data management",
      "MDM",
      "data standards",
      "data stewardship",
      "information governance",
      "data protection",
      "data sharing",
      "open data",
      "data interoperability",
      // Analytics & BI
      "data analytics",
      "business intelligence",
      "BI platform",
      "reporting solution",
      "data visualisation",
      "data visualization",
      "dashboard",
      "Power BI",
      "Tableau",
      "Qlik",
      "Looker",
      "performance analytics",
      "statistical analysis",
      "KPI reporting",
      // Roles & services
      "data science",
      "data scientist",
      "data engineer",
      "data architect",
      "data analyst",
      "data collection",
      "data directorate",
      "data transformation portfolio",
      // Government-specific
      "management information",
      "MI build",
      "learner data",
      "learner record",
      "management information system",
    ],

    // ── Artificial intelligence & machine learning ────────────────────────
    ai: [
      // Core AI/ML
      "artificial intelligence",
      "machine learning",
      "deep learning",
      "neural network",
      "foundation model",
      "large language model",
      "LLM",
      "generative AI",
      "GenAI",
      "GPT",
      "natural language processing",
      "NLP",
      "natural language understanding",
      "computer vision",
      "speech recognition",
      "optical character recognition",
      "OCR",
      "sentiment analysis",
      "text analytics",
      "text mining",
      // Applied AI
      "predictive analytics",
      "predictive modelling",
      "recommendation engine",
      "intelligent automation",
      "robotic process automation",
      "RPA",
      "automated decision",
      "decision intelligence",
      "AI-assisted",
      "AI-powered",
      "AI-enabled",
      // Platforms & tools
      "Azure AI",
      "Microsoft AI",
      "Azure OpenAI",
      "OpenAI",
      "copilot",
      "Microsoft Copilot",
      "cognitive services",
      "AI platform",
      "ML platform",
      "MLOps",
      "vector search",
      "semantic search",
      "retrieval augmented generation",
      "embedding",
      "AI assistant",
      "virtual assistant",
      "chatbot",
      "conversational AI",
      // Strategy & governance
      "AI strategy",
      "AI governance",
      "responsible AI",
      "explainable AI",
      "algorithmic transparency",
      "AI adoption",
      "AI readiness",
    ],

    // ── Justice & courts technology ───────────────────────────────────────
    justice: [
      // Courts & tribunals
      "HMCTS",
      "HM Courts",
      "HM Tribunals",
      "Ministry of Justice",
      "MoJ",
      "courts reform",
      "court digitisation",
      "court technology",
      "digital court",
      "tribunal service",
      "magistrates court",
      "crown court",
      "family court",
      "civil court",
      // Programmes & systems
      "CFT",
      "Common Platform",
      "Justice Digital",
      "digital justice",
      "pre-recorded evidence",
      "evidence management",
      "case management",
      "legal case management",
      "disclosure",
      // Probation & prisons
      "probation",
      "National Probation Service",
      "NPS",
      "HMPPS",
      "HM Prison",
      "offender management",
      "reoffending",
      "community rehabilitation",
      // Criminal justice
      "criminal justice",
      "Crown Prosecution Service",
      "CPS",
      "police digital",
      "law enforcement",
      "forensic",
      "legal aid",
      "legal services",
      "sentencing",
      "victim services",
    ],

    // ── Education, skills & learning ─────────────────────────────────────
    education: [
      // Departments & regulators
      "Department for Education",
      "DfE",
      "ESFA",
      "Education and Skills Funding",
      "Ofsted",
      "Ofqual",
      "Office for Students",
      "OfS",
      "HESA",
      // Schools — types
      "school",
      "primary school",
      "secondary school",
      "infant school",
      "junior school",
      "sixth form",
      "free school",
      "grammar school",
      "state school",
      "maintained school",
      "independent school",
      "academy",
      "multi-academy trust",
      "pupil referral unit",
      "PRU",
      "alternative provision",
      // Schools — data & systems
      "school data",
      "pupil data",
      "school census",
      "National Pupil Database",
      "NPD",
      "school MIS",
      "SIMS",
      "Bromcom",
      "school finance",
      "school funding",
      "school roll",
      "parent portal",
      "school improvement",
      // Schools — qualifications & curriculum
      "GCSE",
      "A-Level",
      "key stage",
      "curriculum",
      "attendance",
      "exclusions",
      "behaviour management",
      "pupil premium",
      "safeguarding",
      "special educational needs",
      "SEND",
      // Universities & higher education
      "university",
      "higher education",
      "Russell Group",
      "research university",
      "undergraduate",
      "postgraduate",
      "degree apprenticeship",
      "student enrolment",
      "student records",
      "student services",
      "student experience",
      "student loan",
      "Student Loans Company",
      "SLC",
      "UCAS",
      "JISC",
      "research data management",
      "knowledge transfer",
      "Research Excellence Framework",
      "Teaching Excellence Framework",
      "academic",
      "faculty",
      "campus",
      // Further education & skills
      "further education",
      "FE college",
      "early years",
      "childcare",
      "apprenticeship",
      "skills bootcamp",
      "T-Level",
      "vocational training",
      "training provider",
      "skills funding",
      "skills strategy",
      "workforce development",
      "lifelong learning",
      // Data & EdTech
      "education data",
      "learner record",
      "learner data",
      "student information",
      "management information system",
      "learning analytics",
      "EdTech",
      "virtual learning environment",
      "VLE",
      "education management",
    ],

    // ── Software delivery, architecture & technical services ──────────────
    delivery: [
      // Engineering
      "software engineering",
      "software development",
      "application development",
      "web development",
      "API development",
      "microservices",
      "cloud native",
      "DevOps",
      "DevSecOps",
      "continuous integration",
      "CI/CD",
      "containerisation",
      "Docker",
      "Kubernetes",
      "infrastructure as code",
      "site reliability",
      "SRE",
      // Architecture
      "technical architecture",
      "solution architecture",
      "enterprise architecture",
      "system integration",
      "systems integration",
      "integration services",
      "API integration",
      // Testing & quality
      "quality assurance",
      "software testing",
      "test automation",
      "test centre of excellence",
      "user acceptance testing",
      "performance testing",
      "security testing",
      // Delivery methodology
      "agile development",
      "agile delivery",
      "agile team",
      "scrum",
      "kanban",
      "product delivery",
      "product management",
      "business analysis",
      "programme delivery",
      "portfolio management",
      // User-centred
      "user centred design",
      "user research",
      "service design",
      "UX design",
      "interaction design",
      "accessibility",
      "WCAG",
      "GDS service standard",
      "discovery",
      "alpha",
      "beta",
      // Engagement models
      "delivery partner",
      "managed service",
      "digital delivery",
      "digital partner",
      "outcome-based",
      "statement of work",
      // Frameworks & procurement routes
      "digital specialists",
      "digital outcomes",
      "Digital Outcomes and Specialists",
      "DOS",
      "G-Cloud",
      "G Cloud",
      "RM6263",
      "Digital Specialists and Programmes",
      "Crown Commercial Service",
      "CCS framework",
      "framework agreement",
      "call off",
    ],

    // ── Consulting & technology strategy ─────────────────────────────────
    consulting: [
      // Transformation
      "digital transformation",
      "IT transformation",
      "legacy modernisation",
      "IT modernisation",
      "technology strategy",
      "digital strategy",
      "technology consulting",
      "IT strategy",
      "IT consultancy",
      "strategic advisory",
      "operating model",
      "target operating model",
      "organisational design",
      "change management",
      "change programme",
      "transformation programme",
      "business transformation",
      "innovation",
      "proof of concept",
      "feasibility study",
      "options appraisal",
      "business case",
      "strategic review",
      // Cloud
      "cloud migration",
      "cloud adoption",
      "cloud strategy",
      "cloud first",
      "hybrid cloud",
      "multi-cloud",
      "Azure",
      "Microsoft Azure",
      "Microsoft 365",
      "M365",
      "Google Cloud",
      "GCP",
      "AWS",
      "Amazon Web Services",
      "cloud platform",
      // Government programmes
      "BDUK",
      "Building Digital UK",
      "Government Digital Service",
      "spend controls",
      "service assessment",
    ],

    // ── Housing & social sector ───────────────────────────────────────────
    housing: [
      // Organisation types
      "housing association",
      "housing provider",
      "registered provider",
      "registered social landlord",
      "RSL",
      "social housing",
      "affordable housing",
      "council housing",
      "shared ownership",
      "leasehold management",
      // Operations & management
      "housing management",
      "housing management system",
      "housing technology",
      "property management",
      "asset management",
      "stock condition",
      "housing portfolio",
      "void properties",
      "lettings",
      "allocations",
      "rent collection",
      "arrears management",
      "tenancy management",
      "tenants",
      "residents",
      "resident portal",
      "housing CRM",
      // Repairs & compliance
      "responsive repairs",
      "planned maintenance",
      "cyclical maintenance",
      "reactive maintenance",
      "building safety",
      "fire safety",
      "cladding",
      "damp and mould",
      "housing compliance",
      "energy efficiency",
      "retrofit",
      "decarbonisation",
      // Regulators & policy
      "STAIRS",
      "Awaab",
      "RSH",
      "Regulator of Social Housing",
      "MHCLG",
      "HACT",
      "housing ombudsman",
      "housing benefit",
      "Right to Buy",
      // Specialist housing
      "homelessness",
      "temporary accommodation",
      "sheltered housing",
      "supported housing",
      "extra care housing",
      "housing needs",
      // Data & analytics
      "housing data",
      "housing analytics",
      "housing revenue account",
      "neighbourhood management",
      "estate management",
    ],
  },

  // ── BUYER KEYWORDS (flag tenders from these organisations) ───────────────
  // Drawn from Solirius's awarded contract history + high-value adjacent buyers.
  targetBuyers: [
    // Justice & policing
    "Ministry of Justice",
    "HMCTS",
    "HM Courts",
    "Crown Prosecution Service",
    "probation",
    "HMPPS",
    "Home Office",
    "Border Force",
    "police",
    "fire service",
    "Independent Office for Police Conduct",
    // Education & skills
    "Department for Education",
    "ESFA",
    "Education and Skills Funding",
    "Ofsted",
    // Health & welfare
    "NHS",
    "NHS England",
    "NHS Digital",
    "Department of Health",
    "DHSC",
    "Department for Work and Pensions",
    "DWP",
    "Money and Pensions",
    // Central government — technology & digital
    "Cabinet Office",
    "Government Digital Service",
    "GDS",
    "DSIT",
    "DCMS",
    "Department for Business and Trade",
    "DBT",
    "BEIS",
    // Foreign & security
    "FCDO",
    "Foreign Commonwealth",
    "Ministry of Defence",
    "MOD",
    "Defence",
    // Economic regulation & finance
    "Ofgem",
    "HM Revenue",
    "HMRC",
    "HM Treasury",
    "Financial Conduct Authority",
    "FCA",
    "Competition and Markets Authority",
    "CMA",
    "Office for National Statistics",
    "ONS",
    // Infrastructure & environment
    "Planning Inspectorate",
    "Environment Agency",
    "Natural England",
    "Homes England",
    "Department for Transport",
    "DVLA",
    "Companies House",
    "Land Registry",
    // Research & innovation
    "UKRI",
    "UK Research and Innovation",
    "Innovate UK",
    // Housing & local government
    "housing",
    "council",
    "local authority",
    "MHCLG",
    "Department for Levelling Up",
    "DLUHC",
    "Greater London Authority",
    "GLA",
    "Transport for London",
    "TfL",
    // Devolved governments
    "Scottish Government",
    "Welsh Government",
    "Northern Ireland Executive",
  ],

  // ── EXCLUDED REFERENCES ──────────────────────────────────────────────────
  // Add Contracts Finder reference numbers (e.g. "CA18069") to suppress
  // specific notices that match keywords but are not relevant.
  excludeRefs: [
    "CA18069",
  ],

  // ── VALUE THRESHOLDS ─────────────────────────────────────────────────────
  minValue: 50_000,   // ignore tiny tenders below this (£)
  maxValue: null,     // no upper cap

  // ── OUTPUT ───────────────────────────────────────────────────────────────
  outputDir: "./output",
  dataDir: "./data",
};
